### ISSUE TITLE
config:publish throws an exception

### ISSUE THREAD

**Issue by borys-p** [nWidart/Laravel-forecast#1]
Hi,

Probably there's a problem with L5.1:

```
>php artisan config:publish nwidart/laravel-forecast

  [BadMethodCallException]
  Call to undefined method [package]
```

**Comment by nWidart** [comment]
It's indeed still using the old l4 way.
I'll update it asap.

**Comment by borys-p** [comment]
Great, looking forward to it!

I patched it a little to get it working, but it's nothing to be proud of.

**Comment by nWidart** [comment]
Sorry for the delay! Laravel 5 support is now available. :smile:

**Comment by borys-p** [comment]
Great, going to test it :)
