### ISSUE TITLE
Store all configuration in config file

### ISSUE THREAD

**Issue by borys-p** [nWidart/Laravel-forecast#2]
Hi,

Currently this library is a thin wrapper around forecast-php and stores only the API_KEY in config file. Still we have to pass all the extra params in the runtime (like "lang", "units", etc.). It would be great to have them all in the config file and use this library fully "the Laravel way", like:

```
public function index(Forecast $forecast)
{
    $data = $forecast->get(53.1194,18.0044);  // or get(lat, lng, time)
    // (...)
}
```

**Comment by nWidart** [comment]
The base php package we use ( https://github.com/guhelski/forecast-php ) does not allow for this, since it's setting those arguments in the get method.

I plan on creating a php package myself that's better tested using Guzzle, I'll also enable this feature.

**Comment by borys-p** [comment]
But you could use the `get` method directly on the wrapper and pass the extra params to the underlying forecast-php from the config if they are not provided in the method call.

**Comment by nWidart** [comment]
It's now possible to set the options globally for every request, in version [2.1](https://github.com/nWidart/Laravel-forecast/releases/tag/2.1)
